<?php

/***************************************************
 *	SERVERCON.PHP - Establishes database connection
 *
 *		Runs every time a page is opened.
 */

	// variables for accessing the database
	// Host for the database, usually this will be localhost (ie. it is hosted in the same place as the rest of your files
	$dbhost = "deco3801-01.zones.eait.uq.edu.au";
	// Username & password for accessing the database, you can use phpMyAdmin to create users for your database
	$dbuser = "root";
	$dbpass = "Viking8Chief+latch";
	// Database to be accessed - replace this with the name you've given to your database
	$dbname = "aeb";
	
	// Ensure that all errors are being output to the php error log
	// This can be found on your zone, SSH into your zone, navigate to /var/log/php, type cat error.log to print out any errors generated by PHP
	//error_reporting(E_ALL);
	
	// Connect to the MySQL server - if an error occurs, the "die" message will be output to the log
	$dbconn = new mysqli($dbhost, $dbuser, $dbpass, $dbname);
	if(!$dbconn){
		die("Unable to connect to database [".mysqli_connect_error()."]");
	}
?>